### ISSUE TITLE
Can't transfer save game

### ISSUE THREAD

**Issue by charlesmckee47** [Gronis/gb-save-manager#1]
Hi this is the person from Reddit that was having trouble uploading a save to their Pokemon yellow and you asked to see the file structure of the flashcard here is a zip with all the files
[Flash card file structure.zip](https://github.com/Gronis/gb-save-manager/files/14394771/Flash.card.file.structure.zip)

**Comment by Gronis** [comment]
Weird, that looks ok. If you open the save file inside a hex editor (Easiest is to try one online like this one: https://hexed.it/), how does it look there? Is it all 1s/0s or does it look like actual save data?

**Comment by Gronis** [comment]
For reference, here is what a Donkey Kong Land save looks like in that hex editor:
<img width="681" alt="Screenshot 2024-02-25 at 01 05 32" src="https://github.com/Gronis/gb-save-manager/assets/5390421/a6164067-cef7-4809-b746-081465f1bbb0">

**Comment by charlesmckee47** [comment]
Looking at it compared to the original file it looks the same a bunch of f

**Comment by charlesmckee47** [comment]
Also I forgot to mention this this might be something that will help this is a save that was converted from a virtual console save to a save that works on GB flash card

**Comment by Gronis** [comment]
> Looking at it compared to the original file it looks the same a bunch of f

This is a bad sign. F is hex code for 15 (decimal), which is the same as 11111111 in binary (all 1's). The virtual console save conversion probably failed.

Have you tried to load the save in an emulator or on the EVERDRIVE with Pokemon Yellow rom after the conversion to make sure the save file works there? It is very likely that the save file is corrupt/broken.

**Comment by charlesmckee47** [comment]
yeah if I put it on my Pokemon ROM and booted up it'll let me continue just like as if it was playing from real cart

**Comment by Gronis** [comment]
Maybe you can send the save file and I can see if I can load it onto my pokemon yellow cartridge? Or does it contain sensitive information?

**Comment by charlesmckee47** [comment]
okay never mind it was working but for some reason it wiped itself

**Comment by charlesmckee47** [comment]
oh this is going to be fun not going to remember how the heck to make a 3DS VC save into a regular game save

**Comment by charlesmckee47** [comment]
Okay trying again with a new save that was good got a little glitch box and then nothing is showing in terms of flashing

**Comment by charlesmckee47** [comment]
I am mad that was the whole entire problem a bad save file that somehow I didn't find out about until you said something about checking the hex

**Comment by Gronis** [comment]
Sad to hear that your save file is bad. At least we found the problem.

**Comment by charlesmckee47** [comment]
Well I was just able to go grab the safe from my 3DS and I was able to still get the save to work
